services:
  # Backend API Service
  - type: web
    name: galileo-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  # Frontend Service
  - type: web
    name: galileo-frontend
    runtime: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    rootDir: .
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_API_URL
        value: https://galileo-backend.onrender.com
      - key: PORT
        generateValue: true